default: &default
  adapter: postgresql
  host: localhost

  pool: 50

  timeout: 5000

development:
  <<: *default
  database: businessmanagement
  user: acroton
  password: 'qwer1234'

production:
  <<: *default
  database: businessmanagement
  username: root
  password: businessmanagement
